name: Build and Deploy

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main

  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Stack to deploy'
        required: false
        default: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Verify tree structure
#        working-directory: ./
#        run: |
#          pwd
#          echo "Current directory contents:"
#          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Backend build
      - name: Cache backend dependencies
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

#      - name: Verify tree structure
#        working-directory: ./
#        run: |
#          pwd
#          echo "Current directory contents:"
#          ls -la

      - name: Build backend
        working-directory: ./backend
        run: npm run build

#      - name: Verify tree structure
#        working-directory: ./
#        run: |
#          pwd
#          echo "Current directory contents:"
#          ls -la

      # Frontend build
      - name: Cache frontend dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

#      - name: Install frontend dependencies
#        working-directory: ./frontend
#        run: npm ci

#      - name: Verify tree structure
#        working-directory: ./frontend
#        run: |
#          pwd
#          echo "Current directory contents:"
#          ls -la

#      - name: Build frontend
#        working-directory: ./frontend
#        run: npm run build

#      - name: Verify frontend build
#        working-directory: ./frontend
#        run: |
#          if [ ! -d "build" ]; then
#            echo "Frontend build directory does not exist!"
#            exit 1
#          fi
#          ls -la build/

      # Infrastructure build and CDK synth
      - name: Cache infrastructure dependencies
        uses: actions/cache@v4
        with:
          path: infrastructure/node_modules
          key: ${{ runner.os }}-infra-${{ hashFiles('infrastructure/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-infra-

      - name: Install infrastructure dependencies
        working-directory: ./infrastructure
        run: npm ci

      - name: Build infrastructure
        working-directory: ./infrastructure
        run: npm run build

      - name: Verify infrastructure build
        working-directory: ./infrastructure
        run: |
          if [ ! -d "lib" ]; then
            echo "Infrastructure lib directory does not exist!"
            exit 1
          fi
          ls -la lib/

      - name: CDK Synthesize
        working-directory: ./infrastructure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Frontend build directory exists: $(test -d ../frontend/build && echo 'YES' || echo 'NO')"
          echo "Running CDK synth..."
          npm run cdk:build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy backend infrastructure
        working-directory: ./infrastructure
        run: npm run cdk:deploy:backend

      - name: Deploy frontend infrastructure
        working-directory: ./infrastructure
        run: npm run cdk:deploy:frontend

      - name: Print build completion message
        run: echo "Build and deployment completed successfully!"
